name: lineage_viewer
channels:
  - defaults
dependencies:
  - mayavi=4.7.1
  - numpy=1.16.5
  - pillow=8.3.1
  - python=3.6.9
  - scipy=1.3.1
  - vtk=8.2.0
  - pip:
    - opencv-contrib-python==3.4.2.16
    - opencv-python==4.1.2.30
    - pyqt5==5.15.4
    - tqdm==4.46.0